services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: db_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/bitnami/postgresql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valorant-api
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=postgres
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
